# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Social' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Social
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'JGProgressHUD'

end
